spring.application.name=Makeup-dev
logging.level.com.example.Makeup=DEBUG

########### CONFIG CONNECT MYSQL (Docker Compose service)
spring.datasource.url=jdbc:mysql://mysql:3306/makeup?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}

########### Config JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

########### CONFIG RabbitMQ (Docker)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

########### CONFIG Redis
spring.redis.host=redis-dev
spring.redis.port=6379
