CREATE TABLE product (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name_product VARCHAR(255) NOT NULL,
    description VARCHAR(250),
    size VARCHAR(10) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    status TINYINT(1),
    image VARCHAR(255),
    current_quantity INT NOT NULL,
    quantity INT NOT NULL,
    version INT NOT NULL,
    rental_count INT,
    sub_category_id BIGINT UNSIGNED,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_product_sub_category FOREIGN KEY (sub_category_id) REFERENCES sub_category(id)
);



INSERT INTO `product` (id, name_product, description, size, price, status, image, current_quantity, quantity, version, rental_count, sub_category_id, created_at, updated_at)
VALUES
(UUID(), 'Christmas Elf Women Girls Family Costumes', 'a', 'X', 30, 1, 'elfwomen1.jpg,elfwomen2.jpg,elfwomen3.jpg,elfwomen4.jpg,elfwomen5.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'Red Children Christmas Costumes with Cute Hat', 'a', 'X', 30, 1, 'redchild1.jpg,redchild2.jpg', 100, 100, 1, 2, 19, NOW(), NOW()),
(UUID(), 'Green Child Christmas Costume with Colorful Snowball', 'a', 'X', 30, 1, 'greenchild1.jpg,greenchild2.png,greenchild3.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'Christmas costumes women party dress with white gloves', 'a', 'X', 30, 1, 'christmas1.jpg,christmas2.jpg,christmas3.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'Christmas Santa Claus Costume With The Beard So Smart', 'a', 'X', 30, 1, 'santa1.png,santa3.jpg,santa2.png,santa4.jpg,santa5.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'Christmas Elf Cosplay Dress Red Mixed Green Costume for Christmas Party', 'a', 'X', 30, 1, 'elfmixed1.jpg,elfmixed2.jpg,elfmixed3.jpg,elfmixed4.jpg,elfmixed5.jpg,elfmixed6.jpg,elfmixed8.jpg,elfmixed9.jpg,elfmixed11.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'The new Christmas dress party dress Christmas costumes performing long-sleeved dress', 'a', 'X', 30, 1, 'newchristmas1.jpg,newchristmas2.jpg,newchristmas3.jpg,newchristmas4.jpg,newchristmas6.jpg,newchristmas7.jpg,newchristmas8.jpg,newchristmas9.jpg,newchristmas11.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'New Style Women Christmas Santa Claus Costumes', 'a', 'X', 30, 1, 'newstyle1.jpg,newstyle2.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'Latest shawl Christmas dress party dress Christmas costume splited detachable skirt', 'a', 'X', 30, 1, 'shawl1.jpg,shawl2.jpg,shawl3.jpg,shawl4.jpg,shawl6.jpg,shawl8.jpg,shawl9.jpg,shawl11.jpg', 100, 100, 1, 1, 19, NOW(), NOW()),
(UUID(), 'Deluxe Penguin Halloween Animal Costume Cute cartoon maomao Uniform', 'a', 'X', 30, 1, 'penguin.jpg', 100, 100, 1, 1, 18, NOW(), NOW()),
(UUID(), 'Halloween Witch Long Dress Cosplay Costume', 'a', 'X', 30, 1, 'witch1.jpg,witch2.jpg,witch3.jpg,witch4.jpg,witch5.jpg', 100, 100, 1, 0, 18, NOW(), NOW()),
(UUID(), 'Party Witch Costume Halloween Costume Masquerade Performance Costume', 'a', 'X', 30, 1, 'partywitch1.jpg,partywitch2.jpg,partywitch3.jpg,partywitch4.jpg', 100, 100, 1, 5, 18, NOW(), NOW()),
(UUID(), 'Vocaloid Hatsune Miku Rascal Cosplay Meiko Cosplay Costume', 'a', 'X', 30, 1, 'vocaloid1.jpg,vocaloid2.jpg,vocaloid3.jpg,vocaloid4.jpg,vocaloid5.jpg,vocaloid6.jpg', 100, 100, 1, 0, 18, NOW(), NOW()),
(UUID(), 'Halloween Cute Witch Cosplay Costume', 'a', 'X', 30, 1, 'sexywitch1.jpg,sexywitch2.jpg,sexywitch3.jpg,sexywitch4.jpg', 100, 100, 1, 4, 18, NOW(), NOW()),
(UUID(), 'Halloween Witch Cosplay Costume', 'a', 'X', 30, 1, 'halloweenwitch1.jpg,halloweenwitch2.jpg,halloweenwitch3.jpg,halloweenwitch4.jpg,halloweenwitch5.jpg,halloweenwitch6.jpg', 100, 100, 1, 1, 18, NOW(), NOW()),
(UUID(), 'Halloween Vintage Dress Two Colors Cosplay Costume', 'a', 'X', 30, 1, 'vintage2.jpg,vintage4.jpg,vintage5.jpg,vintage6.jpg,vintage7.jpg,vintage9.jpg,vintage10.jpg', 100, 100, 1, 1, 18, NOW(), NOW()),
(UUID(), 'Addams Family Morticia Halloween Cosplay Costume', 'a', 'X', 30, 1, 'addams1.jpg,addams2.jpg,addams3.jpg,addams4.jpg,addams5.jpg,addams6.jpg', 100, 100, 1, 0, 18, NOW(), NOW()),
(UUID(), 'Halloween Cloaks Witch Cosplay Costumes Fancy Balls Costumes', 'a', 'X', 30, 1, 'cloaks1.jpg,cloaks2.jpg,cloaks3.jpg,cloaks4.jpg,cloaks5.jpg,cloaks6.jpg', 100, 100, 1, 0, 18, NOW(), NOW()),
(UUID(), 'Halloween Witch Dress Vampires Cosplay Costume', 'a', 'X', 30, 1, 'vampires1.jpg,vampires2.jpg,vampires3.jpg,vampires5.jpg,vampires6.jpg,vampires7.jpg', 100, 100, 1, 0, 18, NOW(), NOW()),
(UUID(), 'Movie Mary Shaw Halloween Dress Cosplay Costume', 'a', 'X', 30, 1, 'marryshaw1.jpg,marryshaw2.jpg,marryshaw3.jpg,marryshaw5.jpg,marryshaw6.jpg,marryshaw7.jpg,marryshaw8.jpg', 100, 100, 1, 0, 18, NOW(), NOW()),
(UUID(), 'The Hydro Archon Dark Furina de Fontaine Focalors Cosplay Costume', 'a', 'X', 30, 1, 'furina1.jpg,furina2.jpg,furina3.jpg,furina4.jpg,furina5.jpg,furina6.jpg,furina7.jpg,furina8.jpg', 100, 100, 1, 0, 16, NOW(), NOW()),
(UUID(), 'Lantern Rite Twilight Blossom Ganyu Cosplay Costume', 'a', 'X', 30, 1, 'ganyu1.jpg,ganyu2.jpg,ganyu3.jpg,ganyu4.jpg,ganyu5.jpg,ganyu6.jpg,ganyu7.jpg,ganyu8.jpg,ganyu9.jpg,ganyu10.jpg,ganyu11.jpg,ganyu12.jpg', 100, 100, 1, 0, 16, NOW(), NOW()),
(UUID(), 'Mavuika Cosplay Costume Halloween Costume — Standard Edition', 'a', 'X', 30, 1, 'maivuika1.jpg,maivuika2.jpg,maivuika3.jpg,maivuika4.jpg,maivuika5.jpg,maivuika6.jpg,maivuika7.jpg,maivuika8.jpg,maivuika9.jpg,maivuika10.jpg,maivuika11.jpg,maivuika12.jpg,maivuika13.jpg,maivuika14.jpg,maivuika15.jpg', 100, 100, 1, 6, 16, NOW(), NOW()),
(UUID(), 'Baal Raiden Shogun Magatsu Mitake Narukami no Mikoto Purple Long Cosplay Wigs', 'a', 'X', 30, 1, 'raiden1.jpg,raiden2.jpg,raiden3.jpg,raiden4.jpg,raiden5.jpg,raiden6.jpg,raiden7.jpg,raiden8.jpg,raiden9.jpg,raiden10.jpg', 100, 100, 1, 2, 16, NOW(), NOW()),
(UUID(), 'Lantern Rite Frostflower Dew Shenhe Cosplay Costume', 'a', 'X', 30, 1, 'shenhe1.jpg,shenhe2.jpg,shenhe3.jpg,shenhe4.jpg,shenhe5.jpg,shenhe6.jpg,shenhe7.jpg,shenhe8.jpg,shenhe9.jpg', 100, 100, 1, 9, 16, NOW(), NOW()),
(UUID(), 'Honkai Impact 3rd Aponia Blonde Cosplay Wigs', 'a', 'X', 30, 1, 'aponia1.jpg,aponia2.jpg,aponia3.jpg,aponia4.jpg,aponia5.jpg', 100, 100, 1, 2, 13, NOW(), NOW()),
(UUID(), 'Honkai Impact 3rd Elysia Cosplay Costume', 'a', 'X', 30, 1, 'elysia1.jpg,elysia2.jpg,elysia3.jpg,elysia4.jpg,elysia5.jpg,elysia6.jpg,elysia7.jpg,elysia8.jpg,elysia9.jpg', 100, 100, 1, 5, 13, NOW(), NOW()),
(UUID(), 'EVA Asuka Honkai Impact 3rd Collaboration Cosplay Costume', 'a', 'X', 30, 1, 'hkasuka01.jpg,hkasuka02.jpg,hkasuka03.jpg,hkasuka04.jpg,hkasuka05.jpg,hkasuka06.jpg,hkasuka07.jpg,hkasuka08.jpg,hkasuka09.jpg,hkasuka10.jpg', 100, 100, 1, 7, 13, NOW(), NOW()),
(UUID(), 'Honkai Star Rail Firefly Cosplay Costume', 'a', 'X', 30, 1, 'firefly1.jpg,firefly2.jpg,firefly3.jpg,firefly4.jpg,firefly5.jpg,firefly6.jpg,firefly7.jpg,firefly8.jpg,firefly9.jpg,firefly10.jpg', 100, 100, 1, 8, 15, NOW(), NOW()),
(UUID(), 'Honkai Star Rail Kafka Cosplay Shoes', 'a', 'X', 30, 1, 'kafka1.png,kafka2.png,kafka3.png,kafka4.png', 100, 100, 1, 3, 15, NOW(), NOW()),
(UUID(), 'Sparkle Honkai Star Rail Cosplay Costume', 'a', 'X', 30, 1, 'sparkle1.jpg,sparkle2.jpg,sparkle3.jpg,sparkle4.jpg,sparkle5.jpg,sparkle6.jpg,sparkle7.jpg,sparkle8.jpg', 100, 100, 1, 2, 15, NOW(), NOW()),
(UUID(), 'Honkai Star Rail Yunli Cosplay Costume', 'a', 'X', 30, 1, 'yunli1.jpg,yunli2.jpg,yunli3.jpg,yunli4.jpg,yunli5.jpg,yunli6.jpg,yunli7.jpg,yunli8.jpg,yunli9.jpg', 100, 100, 1, 8, 15, NOW(), NOW()),
(UUID(), 'LOL Wild Rift The Nine-Tailed Fox Ahri Cosplay Costume', 'a', 'X', 30, 1, 'ahri1.jpg,ahri2.jpg,ahri3.jpg,ahri4.jpg,ahri5.jpg,ahri6.jpg,ahri7.jpg,ahri8.jpg,ahri9.jpg,ahri10.jpg,ahri11.jpg', 100, 100, 1, 0, 14, NOW(), NOW()),
(UUID(), 'LOL Heartache & Heartthrob Caitlyn Cosplay Costume Halloween Costume', 'a', 'X', 30, 1, 'caitlyn1.jpg,caitlyn2.jpg,caitlyn3.jpg,caitlyn4.jpg,caitlyn5.jpg,caitlyn6.jpg,caitlyn7.jpg,caitlyn8.jpg,caitlyn9.jpg,caitlyn10.jpg,caitlyn11.jpg,caitlyn12.jpg', 100, 100, 1, 0, 14, NOW(), NOW()),
(UUID(), 'LOL KDA ALL OUT Kaisa Cosplay Costume Halloween Costume', 'a', 'X', 30, 1, 'kaisa1.jpg,kaisa2.jpg,kaisa3.jpg,kaisa4.jpg,kaisa5.jpg,kaisa6.jpg,kaisa7.jpg,kaisa8.jpg,kaisa9.jpg,kaisa10.jpg,kaisa11.jpg', 100, 100, 1, 4, 14, NOW(), NOW()),
(UUID(), 'LOL KDA ALL OUT Kaisa Cosplay Costume Halloween Costume', 'a', 'X', 30, 1, 'silco1.jpg,silco2.jpg,silco3.jpg,silco4.jpg,silco5.jpg,silco6.jpg', 100, 100, 1, 2, 14, NOW(), NOW()),
(UUID(), 'Joker Purple Cosplay Costumes Coat', 'a', 'x', 30, 1, 'joker1.jpg,joker2.jpg,joker3.jpg,joker4.jpg', 100, 100, 1, 1, 8, NOW(), NOW()),
(UUID(), 'Spider-Man Black Cosplay Costume', 'a', 'x', 30, 1, 'spiderman1.jpg,spiderman2.jpg,spiderman3.jpg,spiderman4.jpg', 100, 100, 1, 3, 9, NOW(), NOW()),
(UUID(), 'Spider-Man Miles Morales Jumpsuit Cosplay Costume', 'a', 'x', 30, 1, 'miles1.jpg,miles2.jpg,miles3.jpg,miles4.jpg,miles5.jpg,miles6.jpg', 100, 100, 1, 7, 9, NOW(), NOW()),
(UUID(), 'Spider-Man 2099 Miguel O\'Hara Cosplay Costume Men Halloween Costume', 'a', 'x', 30, 1, 'miguel1.jpg,miguel2.jpg,miguel3.jpg,miguel4.jpg,miguel5.jpg,miguel6.jpg,miguel7.jpg', 100, 100, 1, 9, 9, NOW(), NOW()),
(UUID(), 'Spider-Man Gwen Stacy Cosplay Costume', 'a', 'x', 30, 1, 'stacy1.jpg,stacy2.jpg,stacy3.jpg,stacy4.jpg,stacy5.jpg,stacy6.jpg,stacy7.jpg,stacy8.jpg,stacy9.jpg,stacy10.jpg,stacy11.jpg', 100, 100, 1, 4, 9, NOW(), NOW()),
(UUID(), 'Dragon Ball Super Whis Purple Anime Cosplay Costumes', 'a', 'x', 30, 1, 'whis-purple1.jpg,whis-purple2.jpg,whis-purple3.jpg,whis-purple4.jpg,whis-purple5.jpg,whis-purple6.jpg', 100, 100, 1, 2, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Vegeta Cosplay Shoes Boots Custom-Made', 'a', 'x', 30, 1, 'vegeta3.jpg,vegeta4.jpg', 100, 100, 1, 4, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Vegeta 1st Version Cosplay Costume', 'a', 'x', 30, 1, 'vegeta1.jpg,vegeta2.jpg', 100, 100, 1, 6, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball For Piccolo Uniforms Cosplay Costume Purple', 'a', 'x', 30, 1, 'picolo1.jpg,picolo2.jpg,picolo3.jpg,picolo4.jpg', 100, 100, 1, 8, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Z Cyborg 18Gou Cosplay Boots Shoes', 'a', 'x', 30, 1, 'no18-1.jpg,no18-2.jpg,no18-3.jpg', 100, 100, 1, 9, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Z Android No.17 Cosplay Costume', 'a', 'x', 30, 1, 'no17-1.jpg,no17-2.jpg,no17-3.jpg,no17-4.jpg,no17-5.jpg', 100, 100, 1, 4, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Master Roshi 1st Version Cosplay Costume', 'a', 'x', 30, 1, 'master-roshi1.jpg,master-roshi2.jpg,master-roshi3.jpg,master-roshi4.jpg,master-roshi5.jpg', 100, 100, 1, 2, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Monkey King Son GoKu Kakarot Cosplay Shoes Boots Custom-Made', 'a', 'x', 30, 1, 'goku1.jpg,goku2.jpg,goku3.jpg', 100, 100, 1, 1, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Son Gohan Uniforms Cosplay Costume', 'a', 'x', 30, 1, 'gohan1.jpg,gohan2.jpg,gohan3.jpg,gohan4.jpg', 100, 100, 1, 5, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Chi Chi Cosplay Costume', 'a', 'x', 30, 1, 'chichi1.jpg,chichi2.jpg,chichi3.jpg,chichi4.jpg,chichi5.jpg,chichi6.jpg,chichi7.jpg', 100, 100, 1, 8, 1, NOW(), NOW()),
(UUID(), 'Dragon Ball Z Bulma Anime Cosplay Costumes', 'a', 'x', 30, 1, 'bulma1.jpg,bulma2.jpg,bulma3.jpg,bulma4.jpg,bulma5.jpg,bulma6.jpg,bulma7.jpg,bulma8.jpg', 100, 100, 1, 0, 1, NOW(), NOW()),
(UUID(), 'Jujutsu Kaisen Zenin Mai Cosplay Costume', 'a', 'x', 30, 1, 'mai1.jpg,mai2.jpg,mai3.jpg,mai4.jpg,mai5.jpg,mai6.jpg,mai7.jpg,mai8.jpg,mai9.jpg', 100, 100, 1, 6, 6, NOW(), NOW()),
(UUID(), 'Jujutsu Kaisen Sorcery Fight Yuta Okkotsu Cosplay Costume', 'a', 'x', 30, 1, 'yuta1.jpg,yuta2.jpg,yuta3.jpg,yuta4.jpg,yuta5.jpg,yuta6.jpg', 100, 100, 1, 3, 6, NOW(), NOW()),
(UUID(), 'Anime Jujutsu Kaisen Yuji Itadori Pink mixed Black Men Cosplay Wigs', 'a', 'x', 30, 1, 'itadori1.jpg,itadori2.jpg,itadori3.jpg', 100, 100, 1, 2, 6, NOW(), NOW()),
(UUID(), 'Jujutsu Kaisen Toji Fushiguro Cosplay Costume', 'a', 'x', 30, 1, 'fushiguro1.jpg,fushiguro2.jpg,fushiguro3.jpg,fushiguro4.jpg,fushiguro5.jpg', 100, 100, 1, 6, 6, NOW(), NOW()),
(UUID(), 'Jujutsu Kaisen Sorcery Fight Suguru Geto Uniform Cosplay Costume', 'a', 'x', 30, 1, 'geto1.jpg,geto2.jpg,geto3.jpg,geto4.jpg,geto5.jpg,geto6.jpg', 100, 100, 1, 8, 6, NOW(), NOW()),
(UUID(), 'Anime Jujutsu Kaisen Satoru Gojo Short Grey Men Cosplay Wigs', 'a', 'x', 30, 1, 'gojo1.jpg,gojo2.jpg,gojo3.jpg,gojo4.jpg,gojo5.jpg', 100, 100, 1, 9, 6, NOW(), NOW()),
(UUID(), 'Jujutsu Kaisen Nishimiya Momo Cosplay Costume', 'a', 'x', 30, 1, 'momo1.jpg,momo2.jpg', 100, 100, 1, 4, 6, NOW(), NOW()),
(UUID(), 'One Punch Man Terrible Tornado Cosplay Costumes Customized', 'a', 'x', 30, 1, 'terrible1.jpg,terrible2.jpg,terrible3.jpg', 100, 100, 1, 2, 5, NOW(), NOW()),
(UUID(), 'One Punch Man Speed of Sound Sonic Uniform Cosplay Costume', 'a', 'x', 30, 1, 'speedofsound1.jpg,speedofsound2.jpg', 100, 100, 1, 1, 5, NOW(), NOW()),
(UUID(), 'One Punch Man Saitama Zipper Hoodie Sweater Cosplay Costumes', 'a', 'x', 30, 1, 'onepunchman1.jpg,onepunchman2.jpg,onepunchman3.jpg', 100, 100, 1, 5, 5, NOW(), NOW()),
(UUID(), 'One Punch Man Saitama With Vacant Look Cosplay Costumes Hat', 'a', 'x', 30, 1, 'onepunchman4.jpg,onepunchman5.jpg,onepunchman6.jpg,onepunchman7.jpg', 100, 100, 1, 7, 5, NOW(), NOW()),
(UUID(), 'One Punch Man Hellish Blizzard Cosplay Costume Custom Made', 'a', 'x', 30, 1, 'heliish.jpg', 100, 100, 1, 9, 5, NOW(), NOW()),
(UUID(), 'Dragonball Z Android No.16 Cosplay Costume', '1', 'x', 30, 1, 'no16-1.jpg,no16-2.jpg,no16-3.jpg,no16-4.jpg,no16-5.jpg', 100, 100, 1, 2, 1, NOW(), NOW()),
(UUID(), 'AI', '1', 'x', 30, 1, 'ai1.jpg,ai2.jpg,ai3.jpg,ai4.jpg,ai5.jpg,ai6.jpg', 100, 100, 1, 2, 20, NOW(), NOW()),
(UUID(), 'Aquamarine Hoshino', '1', 'x', 30, 1, 'auquamarine1.jpg,auquamarine2.jpg,auquamarine3.jpg,auquamarine4.jpg', 100, 100, 1, 2, 20, NOW(), NOW()),
(UUID(), 'Oshi no Ko Ruby Hoshino Blonde Mixed Red Cosplay Wigs', '1', 'x', 30, 1, 'ruby1.jpg,ruby2.jpg,ruby3.jpg,ruby4.jpg', 100, 100, 1, 4, 20, NOW(), NOW()),
(UUID(), 'OSHI NO KO Ruby Hoshino Cosplay Costume', '1', 'x', 30, 1, 'ruby5.jpg,ruby6.jpg,ruby7.jpg,ruby8.jpg,ruby9.jpg,ruby10.jpg,ruby11.jpg,ruby12.jpg,ruby13.jpg', 100, 100, 1, 4, 20, NOW(), NOW()),
(UUID(), 'SPY×FAMILY Damian Uniform Cosplay Costume', '1', 'X', 30, 1, 'damian1.jpg,damian2.jpg,damian3.jpg,damian4.jpg,damian5.jpg,damian6.jpg,damian7.jpg,damian8.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'SPY×FAMILY Forger Anya Black Uniform Daily Cosplay Costume', '1', 'X', 30, 1, 'anya1.jpg,anya2.jpg,anya3.jpg,anya4.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'SPY×FAMILY Forger Anya Pink Cosplay Wigs', '1', 'X', 30, 1, 'anya5.jpg,anya6.jpg,anya7.jpg,anya8.jpg,anya9.jpg,anya10.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'SPY x FAMILY Franky Franklin Red Glasses Cosplay Prop', '1', 'x', 30, 1, 'franky1.jpg,franky2.jpg,franky3.jpg,franky4.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'SPY×FAMILY Twilight Loid Forger Cosplay Costume', '1', 'x', 30, 1, 'loid1.jpg,loid2.jpg,loid3.jpg,loid4.jpg,loid5.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'Spy x Family Sylvia Sherwood Cosplay Costume', '1', 'x', 30, 1, 'sylvia1.jpg,sylvia2.jpg,sylvia3.jpg,sylvia4.jpg,sylvia5.jpg,sylvia6.jpg,sylvia7.jpg,sylvia8.jpg,sylvia9.jpg,sylvia10.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'SPY×FAMILY Forger Yor Black Long Cosplay Wigs', '1', 'x', 30, 1, 'yor1.jpg,yor2.jpg,yor3.jpg,yor4.jpg,yor5.jpg,yor6.jpg', 100, 100, 1, 4, 21, NOW(), NOW()),
(UUID(), 'SPY×FAMILY Yor Forger Red Dress Daily Cosplay Costume', '1', 'x', 30, 1, 'yor7.jpg,yor8.jpg,yor9.jpg,yor10.jpg,yor11.jpg,yor12.jpg,yor13.jpg', 100, 100, 1, 4, 21, NOW(), NOW());